[package]
name = "logistic_map"
version = "0.1.0"
authors = []

[lib]
name = "logistic_map"
path = "src/lib.rs"
crate-type = ["dylib"]

[profile.release]
opt-level = 3
codegen-units = 1

[dependencies]
rustler = "0.17.1"
rustler_codegen = "0.17.1"
lazy_static = "0.2"
rayon = "1.0"